# Generated by Django 5.0.7 on 2024-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='company',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
